services:
  nginx:
    image: nginx:alpine
    ports:
      - "${PORT}:8080"
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
    depends_on:
      - app_blue
      - app_green
    command: >
      sh -c "
        apk add --no-cache gettext &&
        envsubst '$$ACTIVE_POOL' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf &&
        nginx -g 'daemon off;'
      "
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}

  app_blue:
    image: ${BLUE_IMAGE}
    ports:
      - "8081:3000"
    environment:
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - APP_POOL=blue

  app_green:
    image: ${GREEN_IMAGE}
    ports:
      - "8082:3000"
    environment:
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - APP_POOL=green
